spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskManager
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true